### ISSUE TITLE
Stopped collecting points

### ISSUE THREAD

**Issue by ashtrayhalo** [trmcnvn/twitch-channel-points#25] opened 2021-05-18 21:47 UTC
I've used this for about 3 months if not longer consecutively and its worked fine, but as of recently it just stopped working. I've uninstalled and reinstalled multiple times. Nothing has worked

**Comment by Whiteland92** [comment] 2021-05-18 22:20
Duplicate of #24

**Closed as completed** 2021-05-20 15:41 UTC
